namespace senac_machine_learning_PI3.Enums.Adult
{
    public enum Native_Country
    {
        United_States  =  1,
        Cambodia = 2,
        England = 3,
        Puerto_Rico = 4,
        Germany = 5,
        Outlying_US = 6,
        Japan = 7,
        Greece = 8,
        South = 9,
        China = 10,
        Cuba = 11,
        Iran = 12,
        Honduras = 13,
        Philippines = 14,
        Italy = 15,
        Poland = 16,
        Jamaica = 17,
        Vietnam = 18,
        Mexico = 19,
        Portugal = 20,
        Ireland = 21,
        France = 22,
        Dominican_Republic = 23,
        Laos = 24,
        Ecuador = 25,
        Taiwan = 26,
        Haiti = 27,
        Columbia = 28,
        Hungary = 29,
        Guatemala = 30,
        Nicaragua = 31,
        Scotland = 32,
        Thailand = 33,
        Yugoslavia = 34,
        El_Salvador = 35,
        Trinadad_and_Tobago = 36,
        Peru = 37,
        Hong = 38,
        Holand_Netherlands = 39,
        Canada = 40,
        India = 41
    }
}
